In [31]:
import numpy as np
import math as math

In [32]:
bina = lambda m:0 if m < 0 else 1
dina = lambda m:1

In [33]:
relu = lambda m:max(0, m)
delu = lambda m:0 if m < 0 else 1

In [68]:
sigm = lambda m:1/(1+np.exp(-m))
digm = lambda m:sigm(m)*(1-sigm(m))

In [35]:
tanh = lambda m:np.tanh(m)
danh = lambda m:1-m**2

In [ ]:
bsigm = lambda m:(2/(1+np.exp(-m)))-1
dsigm = lambda m:0.5*(1-m**2)

2 layer network with 2 neurons

In [ ]:
l1 = np.array((
    [0.5,0.5,0.5],    # n1
    [-0.5,-0.5,-0.5]       # n2
))

l2 = np.array((
    [1,1,1],      # n1
    [1,1,1]     # n2
))

In [ ]:
x1 = np.array([2,2,1])     # includes bias
y = np.array([0.66,0.25])     # target values

NOTE: Keep training from here vvv

In [537]:
# forward pass
z1 = [x1 @ n.T for n in l1]
z1

[2.5, 3.5]

In [538]:
x1 @ l1[0]

2.5

In [539]:
o1 = [tanh(z) for z in z1]
o1

[0.9866142981514303, 0.9981778976111987]

In [540]:
x2 = np.array(o1 + [1]) # new input for layer 2
x2

array([0.9866143, 0.9981779, 1.       ])

In [541]:
z2 = [x2 @ n.T for n in l2]
z2

[2.9845901394874144, 2.4903030124268137]

In [542]:
o2 = [tanh(z) for z in z2]   # final output at the end of the network
o2

[0.994900364297005, 0.986353951030488]

Error calcuation

In [543]:
# Initial error calculation starting from the final layer output
diffs = [d - z for d, z in zip(y, o2)]
deriv = [danh(z) for z in o2]
error = np.array([dif * der for dif, der in zip(diffs, deriv)])


error   # error[0] = error of l2[0]     error[1] = error of l2[1]
sig2 = np.array([
    error[0],   # first neuron error
    error[1]    # second neuron error
    ])

$ \delta_j^{(l)} = f'\!\left(z_j^{(l)}\right) \sum_k w_{jk}^{(l+1)} \, \delta_k^{(l+1)} $

In [544]:
sig1 = np.array([
    0,
    0
])

In [545]:
# Calculate errors for each preceeding neuron
sig1[0] = tanh(z1[0])*(sig2[0]*l2[0][0] + sig2[1]*l2[1][0])
sig1[1] = tanh(z1[1])*(sig2[0]*l2[0][1] + sig2[1]*l2[1][1])

Calculate the deltas

In [546]:
c = 0.01

d2 = np.array((
    [c*sig2[0]*o2[0], c*sig2[0]*o2[1], c*sig2[0]*1],    # weight deltas for output layer neuron 1
    [c*sig2[1]*o2[0], c*sig2[1]*o2[1], c*sig2[1]*1]     # weight deltas for output layer neruon 2
))

d1 = np.array((
    [c*sig1[0]*o1[0], c*sig1[0]*o1[1], c*sig1[0]*1],    # weight deltas for hidden layer neuron 1
    [c*sig1[1]*o1[0], c*sig1[1]*o1[1], c*sig1[1]*1],    # weight deltas for hidden layer neuron 2
))

Weight update

In [547]:
l1 = l1 + d1
l2 = l2 + d2

In [548]:
t = np.concatenate((o1, [1]))

In [549]:
sigm(t @ l2[0])

0.9518684558178941

In [550]:
sigm(t @ l2[1])

0.9234173666680794

In [191]:
l1 = np.array((
    [0.1,0.2,0.3],    # n1
    [-0.1,-0.2,-0.3]       # n2
))

l2 = np.array((
    [1,2,3],      # n1
    [-1,-2,-3]     # n2
))

In [192]:
inputs = np.array([
    [3,4],
    [2,0],
    [6,1],
    [-2,-1], 
    [3,-2], 
    [2,-4],
    [-2,5], 
    [0,2], 
    [-1,0]
])     # includes bias
targets = np.array([
    [1,0],
    [1,0],
    [1,0],
    [0,1],
    [0,0],
    [0,0],
    [1,1],
    [1,1],
    [1,1]
])     # target values

In [193]:
for i in range(1):
    for i, x in enumerate(inputs):
        # 1. Forward pass
        x1 = np.concatenate((x, [1]))
        z1 = [x1 @ n.T for n in l1]
        o1 = [sigm(z) for z in z1]

        x2 = np.array(o1 + [1])         # new input for layer 2 (augmented input)

        z2 = [x2 @ n.T for n in l2]     # dot product scalar
        o2 = [sigm(z) for z in z2]     # final output at the end of the network

        # 2. Initial error calculation starting from the final layer output
        diffs = [d - z for d, z in zip(targets[i], o2)]
        deriv = [digm(z) for z in z2]
        error = np.array([dif * der for dif, der in zip(diffs, deriv)])


        error   # error[0] = error of l2[0]     error[1] = error of l2[1]
        sig2 = np.array([
            error[0],   # first neuron error
            error[1]    # second neuron error
        ])
        
        # 3. Hidden error calculation
        # Calculate errors for each preceeding neuron
        sig1 = np.array([
            digm(z1[0])*(sig2[0]*l2[0][0] + sig2[1]*l2[1][0]),
            digm(z1[1])*(sig2[0]*l2[0][1] + sig2[1]*l2[1][1])
        ])

        # 4. Calculate deltas
        c = 0.5

        d2 = np.array((
            [c*sig2[0]*x2[0], c*sig2[0]*x2[1], c*sig2[0]*1],    # weight deltas for output layer neuron 1
            [c*sig2[1]*x2[0], c*sig2[1]*x2[1], c*sig2[1]*1]     # weight deltas for output layer neruon 2
        ))

        d1 = np.array((
            [c*sig1[0]*o1[0], c*sig1[0]*o1[1], c*sig1[0]*1],    # weight deltas for hidden layer neuron 1
            [c*sig1[1]*o1[0], c*sig1[1]*o1[1], c*sig1[1]*1],    # weight deltas for hidden layer neuron 2
        ))

        # 5. Update the weights
        l1 = l1 + d1
        l2 = l2 + d2
        
        print("\nLayer 1:")
        print(l1)
        print("Layer 2:")
        print(l2)

        # View network output after training cycle
        # Testing the network on untrained data
        print("Prediction of x=(2,2)")
        t1 = np.array([2,2,1])
        t2 = np.array([sigm(t1 @ l1[0]), sigm(t1 @ l1[1]), 1])
        print([sigm(t2@l2[0]), sigm(t2@l2[1])])
    


Layer 1:
[[ 0.10002749  0.20000678  0.30003427]
 [-0.09994502 -0.19998644 -0.29993146]]
Layer 2:
[[ 1.00008662  2.00002136  3.00010798]
 [-1.00008662 -2.00002136 -3.00010798]]
Prediction of x=(2,2)
[0.986471446914436, 0.013528553085563937]

Layer 1:
[[ 0.1000497   0.20002025  0.30006994]
 [-0.09990061 -0.1999595  -0.29986012]]
Layer 2:
[[ 1.00013386  2.00005002  3.00018388]
 [-1.00013386 -2.00005002 -3.00018388]]
Prediction of x=(2,2)
[0.9864744859033787, 0.01352551409662133]

Layer 1:
[[ 0.10007709  0.20002937  0.30010645]
 [-0.0998458  -0.19994125 -0.29978707]]
Layer 2:
[[ 1.00020697  2.00007436  3.0002813 ]
 [-1.00020697 -2.00007436 -3.0002813 ]]
Prediction of x=(2,2)
[0.9864780753484635, 0.013521924651536345]

Layer 1:
[[ 0.09883461  0.19865627  0.29749072]
 [-0.10233036 -0.20268702 -0.3050177 ]]
Layer 2:
[[ 0.9977163   1.99732184  2.99503781]
 [-0.9977163  -1.99732184 -2.99503781]]
Prediction of x=(2,2)
[0.9862651137161713, 0.013734886283828815]

Layer 1:
[[ 0.09807048  0.198032 

In [ ]:
l1 = np.array((
    [0.1,0.2,0.3],    # n1
    [-0.1,-0.2,-0.3]       # n2
))

l2 = np.array((
    [1,2,3],      # n1
    [-1,-2,-3]     # n2
))

y = [1,1]

# 1. Forward pass
x1 = np.array((2,2,1))
z1 = [x1 @ n.T for n in l1]
o1 = [sigm(z) for z in z1]

x2 = np.array(o1 + [1])         # new input for layer 2 (augmented input)

z2 = [x2 @ n.T for n in l2]     # dot product scalar
o2 = [sigm(z) for z in z2]     # final output at the end of the network

# 2. Initial error calculation starting from the final layer output
diffs = [d - z for d, z in zip(y, o2)]
deriv = [digm(z) for z in z2]
error = np.array([dif * der for dif, der in zip(diffs, deriv)])


error   # error[0] = error of l2[0]     error[1] = error of l2[1]
sig2 = np.array([
    error[0],   # first neuron error
    error[1]    # second neuron error
])

# 3. Hidden error calculation
# Calculate errors for each preceeding neuron
sig1 = np.array([
    digm(z1[0])*(sig2[0]*l2[0][0] + sig2[1]*l2[1][0]),
    digm(z1[1])*(sig2[0]*l2[0][1] + sig2[1]*l2[1][1])
])

# 4. Calculate deltas
c = 0.5

d2 = np.array((
    [c*sig2[0]*x2[0], c*sig2[0]*x2[1], c*sig2[0]*1],    # weight deltas for output layer neuron 1
    [c*sig2[1]*x2[0], c*sig2[1]*x2[1], c*sig2[1]*1]     # weight deltas for output layer neruon 2
))

d1 = np.array((
    [c*sig1[0]*o1[0], c*sig1[0]*o1[1], c*sig1[0]*1],    # weight deltas for hidden layer neuron 1
    [c*sig1[1]*o1[0], c*sig1[1]*o1[1], c*sig1[1]*1],    # weight deltas for hidden layer neuron 2
))

# 5. Update the weights
l1 = l1 + d1
l2 = l2 + d2

print("\nLayer 1:")
print(l1)
print("Layer 2:")
print(l2)

# View network output after training cycle
# Testing the network on untrained data
print("Prediction of x=(2,2)")
t1 = np.array([2,2,1])
t2 = np.array([sigm(t1 @ l1[0]), sigm(t1 @ l1[1]), 1])
print([sigm(t2@l2[0]), sigm(t2@l2[1])])

[0.01353230887973933, 0.9864676911202608]
[0.013349185496122658, 0.013349185496122523]
[0.00018065 0.01316854]
0.2055003073422635 * (0.00018064530142646813 + -0.013168540194696057)
0.20550030734226343 * (0.00036129060285293625 + -0.026337080389392115)
[-0.00266902 -0.00533803]

Layer 1:
[[ 0.09905123  0.19961426  0.29866549]
 [-0.10189754 -0.20077148 -0.30266902]]
Layer 2:
[[ 1.00006421  2.00002611  3.00009032]
 [-0.99531892 -1.99809681 -2.99341573]]
Prediction of x=(2,2)
[0.9864146549791476, 0.013728112569124429]


In [205]:
0.5*0.013*1

0.0065